working

diff --git a/.github/workflows/secondary.yaml b/.github/workflows/secondary.yaml
--- a/.github/workflows/secondary.yaml
+++ b/.github/workflows/secondary.yaml
@@ -32,11 +32,10 @@ jobs:
         shell: bash
         run: |
           echo "Hello world"
-          # if [[ "$(($RANDOM % 3))" == "0" ]]; then
-          #   echo "Randomly failing"
-          #   exit 1
-          # fi
-          exit 1
+          if [[ "$(($RANDOM % 2))" == "0" ]]; then
+            echo "Randomly failing"
+            exit 1
+          fi
 
       - name: Update PR comment on success
         if: |
@@ -60,4 +59,4 @@ jobs:
           comment-id: ${{ steps.post_job_link.outputs.comment-id }}
           edit-mode: append
           body: |
-            ... Failed! :exclamation: :warning:
+            ... Failed! :warning:
